apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: nehacodesreviewapp 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nehacodesreviewapp 
    spec:
      containers:
        - name: nehacodesreviewapp 
          image: reviewapp.azurecr.io/nehacodesreviewapp
          ports:
          - containerPort: 80